apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: crud-app
type: Opaque
data:
  POSTGRES_PASSWORD: QXAwMHJQYSQkdzByZCE=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: crud-app
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres-container
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: crud-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: crud-app
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: final_assignment-backend 
          ports:
            - containerPort: 8000
          imagePullPolicy: Never
          env:
           - name: db_address
             value: postgres-service
           - name: db_username
             value: postgres
           - name: db_name
             value: postgres
           - name: db_password
             valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: crud-app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: crud-app
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/postgres
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: crud-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      app: postgres

