---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: crud-app
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/postgres
  storageClassName: ""